[package]
name = "minikernel"
version = "0.1.0"
edition = "2021"
authors = ["arongeo <me@arongeo.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
rustflags = ["--cfg", "peri_mode='low'"]

[dependencies]
